In [1]:
import numpy as np
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Carga de datos y creando sus indices para pasarlos (dato,indice)
train_input = np.asarray(pd.read_csv('train_data_input.csv', sep=',', header=None))
_,train_input_index = np.meshgrid(np.linspace(1,8,8),np.linspace(1,9,9))

train_output = np.asarray(pd.read_csv('train_data_output.csv', sep=',', header=None))
_,train_output_index = np.meshgrid(np.linspace(1,3,3),np.linspace(1,9,9))

test_input = np.asarray(pd.read_csv('test_data_input.csv', sep=',', header=None))
_,test_input_index = np.meshgrid(np.linspace(1,8,8),np.linspace(1,3,3))


In [3]:
# Agrupar puntos en clústers
k = 9
model = KMeans(k)
model.fit(train_input)

print(model.cluster_centers_)

[[0.6858 0.3876 0.216  0.4776 0.4005 0.2199 0.3477 0.2821]
 [0.1077 0.3447 0.3692 0.9981 0.5931 0.3744 0.1872 0.2496]
 [0.7809 0.5145 0.2105 0.8133 0.4473 0.3989 0.2904 0.5733]
 [0.1326 0.264  0.3441 0.1689 0.9041 0.3449 0.4359 0.1287]
 [0.5277 0.7041 0.5487 0.5432 0.8766 0.1965 0.2322 0.6819]
 [0.2172 0.5727 0.4019 0.7227 0.8526 0.135  0.2472 0.3192]
 [0.7902 0.6774 0.3495 0.3462 0.3223 0.1971 0.1831 0.7869]
 [0.6271 0.2841 0.4179 0.4161 0.7674 0.2702 0.2313 0.2646]
 [0.967  0.6667 0.1686 0.9314 0.5616 0.4842 0.4275 0.4518]]


In [11]:
# Extraer centroides
c = model.cluster_centers_

# Calcular el sigma
sigma = (max(c.flatten())-min(c.flatten()))/np.sqrt(2*k)
#sigma = sigma[0]
x=train_input
# Calcular matriz G
p = 9 # Cantidad de muestras
G = np.zeros((p,k))
for i in range(p):
    for j in range(k):
        dist = np.linalg.norm(x[i]-c[j], 2) # Distancia euclideana Entre Xi y Cj
        G[i,j] = np.exp((-1/(sigma**2))*dist**2) # Resultado de la función de activación para Gij

W = np.dot(np.linalg.pinv(G), train_output)

print("Pesos: \n" , W)

Pesos: 
 [[ 9.91525079e-01 -2.58919485e-03 -7.44567157e-05]
 [ 1.04581938e-08  1.00000376e+00 -1.98612024e-03]
 [-2.71725508e-03  9.47481330e-01 -1.95974694e-04]
 [ 9.99876702e-01  7.78207434e-09 -5.75711848e-06]
 [-8.80096386e-05 -3.92499636e-06  9.98961831e-01]
 [-2.09919521e-04 -1.98837953e-03  9.98989696e-01]
 [-7.37915587e-05 -1.79038763e-04  9.99976211e-01]
 [ 9.91392398e-01  9.82391444e-06 -2.91506885e-04]
 [ 1.37881470e-04  9.47474089e-01  1.07516449e-05]]


In [34]:
G = np.zeros((p,k))
for i in range(p):
    for j in range(k):
        dist = np.linalg.norm(x[0,i]-c[j], 2) # Distancia euclideana Entre Xi y Cj
        G[i,j] = np.exp((-1/(sigma**2))*dist**2) # Resultado de la función de activación para Gij

ynew = np.dot(G.T, W) # Salida de la red
print(ynew)

[[ 9.96822630e-01  1.89729368e-03 -2.01521382e-02]
 [ 1.00031720e+00 -1.89398877e-04  2.01214745e-03]
 [ 9.78488811e-01  1.28449169e-02 -1.36432392e-01]
 [ 1.30495659e-02  9.92207749e-01  8.27654723e-02]
 [-1.43668899e-05  1.00000858e+00 -9.11178917e-05]
 [ 1.51757474e-03  9.99093814e-01  9.62503142e-03]
 [-1.54030812e-01  9.19759953e-02  2.30761822e-02]
 [ 6.44708052e-07 -3.09781171e-07  1.00000641e+00]
 [-5.42591990e-04  3.23998792e-04  9.96558741e-01]]


In [6]:
lin = np.linspace(1,5,20)
print(lin.shape)

(20,)
