In [10]:
import numpy as np
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import plot_roc_curve, confusion_matrix, ConfusionMatrixDisplay
from sklearn.datasets import load_wine
import matplotlib.pyplot as plt
import pandas as pd

In [11]:
# Carga de datos
train_input = np.asarray(pd.read_csv('train_data_input.csv', sep=',', header=None))

train_output = np.asarray(pd.read_csv('train_data_output.csv', sep=',', header=None))

test_input = np.asarray(pd.read_csv('test_data_input.csv', sep=',', header=None))

In [27]:
## Entrenamiento no supervisado con algoritmo K-means

# Agrupar puntos en clústers
k = 4 # Numero de neuronas en capa oculta 
model = KMeans(k)
model.fit(train_input)
# Mostramos los puntos de los centroides (en un espacio R^8)
print("Centroides del modelo: \n" , model.cluster_centers_)
print("Iteraciones del K-Means: \n", model.n_iter_)

Centroides del modelo: 
 [[0.1326  0.264   0.3441  0.1689  0.9041  0.3449  0.4359  0.1287 ]
 [0.87395 0.5906  0.18955 0.87235 0.50445 0.44155 0.35895 0.51255]
 [0.65895 0.69075 0.4491  0.4447  0.59945 0.1968  0.20765 0.7344 ]
 [0.65645 0.33585 0.31695 0.44685 0.58395 0.24505 0.2895  0.27335]
 [0.16245 0.4587  0.38555 0.8604  0.72285 0.2547  0.2172  0.2844 ]]


In [28]:
## Entrenamiento supervisado

# Extraer centroides
c = model.cluster_centers_

# Calcular el sigma
sigma = (max(c.flatten())-min(c.flatten()))/np.sqrt(2*k)

x = train_input
# Calcular matriz G
p = 9 # Cantidad de muestras

G = np.zeros((p,k))
for i in range(p):
    for j in range(k):
        dist = np.linalg.norm(x[i]-c[j], 2) # Distancia euclideana Entre Xi y Cj
        G[i,j] = np.exp((-1/(sigma**2))*dist**2) # Resultado de la función de activación para Gij

W = np.dot(np.linalg.pinv(G), train_output)

print("Pesos: \n" , W)

Pesos: 
 [[ 9.99523451e-01 -1.09756614e-04  3.26085141e-05]
 [-9.19529689e-03  1.69846620e+00 -2.26731263e-02]
 [-6.03217229e-03 -4.32921975e-03  7.02292027e+00]
 [ 2.38992545e+00 -8.99344469e-03 -1.62351773e-02]
 [-3.74979823e-03  1.56220926e+00  1.56060187e+00]]


In [30]:
## Predicción de la red

x = test_input
p = 3 # 3 datos de prueba
G = np.zeros((p,k))
for i in range(p):
    for j in range(k):
        dist = np.linalg.norm(x[i]-c[j], 2) # Distancia euclideana Entre Xi y Cj
        G[i,j] = np.exp((-1/(sigma**2))*dist**2) # Resultado de la función de activación para Gij

ynew = np.dot(G, W) # Salida de la red
print(ynew)

[[ 9.47756955e-01 -2.71224034e-03 -4.03331942e-04]
 [ 1.37421345e-03  1.11244464e+00  7.87008724e-03]
 [-7.38741658e-05 -3.45399347e-04  1.19572026e+00]]


In [31]:
## Cálculo del Error

test_output = np.asarray(pd.read_csv('test_data_output.csv', sep=',', header=None))
#error = (test_output - ynew)**2
error = 0
for i in range(3):
    dist = np.linalg.norm(test_output[i]-ynew[i], 2)
    errorprom = dist/3
print(errorprom)
precision = (1-errorprom)*100
print(precision)

0.06524019227638429
93.47598077236157


In [49]:
# Carga de datos
train_input = np.asarray(pd.read_csv('train_data_input copy.csv', sep=',', header=None))

train_output = np.asarray(pd.read_csv('train_data_output copy.csv', sep=',', header=None))

test_input = np.asarray(pd.read_csv('test_data_input copy.csv', sep=',', header=None))
## Entrenamiento no supervisado con algoritmo K-means

# Agrupar puntos en clústers
k = 5 # Numero de neuronas en capa oculta 
model = KMeans(k)
model.fit(train_input)
# Mostramos los puntos de los centroides (en un espacio R^8)
print("Centroides del modelo: \n" , model.cluster_centers_)

## Entrenamiento supervisado

# Extraer centroides
c = model.cluster_centers_

# Calcular el sigma
sigma = (max(c.flatten())-min(c.flatten()))/np.sqrt(2*k)

x = train_input
# Calcular matriz G
p = 6 # Cantidad de muestras

G = np.zeros((p,k))
for i in range(p):
    for j in range(k):
        dist = np.linalg.norm(x[i]-c[j], 2) # Distancia euclideana Entre Xi y Cj
        G[i,j] = np.exp((-1/(sigma**2))*dist**2) # Resultado de la función de activación para Gij

W = np.dot(np.linalg.pinv(G), train_output)

print("Pesos: \n" , W)
## Predicción de la red

x = test_input
p = 3 # 3 datos de prueba
G = np.zeros((p,k))
for i in range(p):
    for j in range(k):
        dist = np.linalg.norm(x[i]-c[j], 2) # Distancia euclideana Entre Xi y Cj
        G[i,j] = np.exp((-1/(sigma**2))*dist**2) # Resultado de la función de activación para Gij

ynew = np.dot(G, W) # Salida de la red
print(ynew)
## Cálculo del Error

test_output = np.asarray(pd.read_csv('test_data_output copy.csv', sep=',', header=None))
#error = (test_output - ynew)**2
error = 0
for i in range(3):
    dist = np.linalg.norm(test_output[i]-ynew[i], 2)
    errorprom = dist/3
print(errorprom)
precision = (1-errorprom)*100
print(precision)

Centroides del modelo: 
 [[0.16245 0.4587  0.38555 0.8604  0.72285 0.2547  0.2172  0.2844 ]
 [0.65645 0.33585 0.31695 0.44685 0.58395 0.24505 0.2895  0.27335]
 [0.87395 0.5906  0.18955 0.87235 0.50445 0.44155 0.35895 0.51255]
 [0.65895 0.69075 0.4491  0.4447  0.59945 0.1968  0.20765 0.7344 ]
 [0.1326  0.264   0.3441  0.1689  0.9041  0.3449  0.4359  0.1287 ]]
Pesos: 
 [[-3.74979823e-03  1.56220926e+00  1.56060187e+00]
 [ 2.38992545e+00 -8.99344469e-03 -1.62351773e-02]
 [-9.19529689e-03  1.69846620e+00 -2.26731263e-02]
 [-6.03217229e-03 -4.32921975e-03  7.02292027e+00]
 [ 9.99523451e-01 -1.09756614e-04  3.26085141e-05]]
[[ 9.99271790e-01  1.69541690e-03  6.27318764e-04]
 [ 9.47756955e-01 -2.71224034e-03 -4.03331942e-04]
 [ 5.23930677e-03  1.00000075e+00  1.31265411e-02]]
0.0047111736682416095
99.52888263317584
